/** @type {import('next').NextConfig} */
const nextConfig = {
  // The preview serves this tree behind a proxy with an arbitrary Host header.
  allowedDevOrigins: ['*'],
  // AGENTS.md in this repo is written by the team, not generated by Next.
  agentRules: false,
};

export default nextConfig;
