/** @type {import('next').NextConfig} */
const nextConfig = {
  // The preview serves the app behind its own host name.
  allowedDevOrigins: ['*'],
  // AGENTS.md in this repo is written by the team, not generated by Next.
  agentRules: false,
};

export default nextConfig;
